### PR TITLE
Add Rome.podspec

### PR DESCRIPTION
**Pull request by thii**
@blender Can you release this to CocoaPods too? We try to manage versions of all the tools that we use, but it's too cumbersome to do it with Homebrew, especially if the formula belongs to a non-core tap.

Let me know if you don't know how to release a podspec.

### CODE REVIEW

**Comment by blender** [comment]
So this makes Rome downloadable via CocoaPods?

Can you please add this method to the Readme too? https://github.com/blender/Rome#get-rome

**Comment by blender** [comment]
@thii I'm guessing I'll just follow this to release a podspec? https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by thii** [comment]
That's right!

**Comment by blender** [comment]
@thii Great! 

May I know what company this project will be used in?
May I add it to https://github.com/blender/Rome#who-uses-rome ?

**Comment by blender** [comment]
@thii 

I'm getting an error when trying to push to trunk.

```
$ pod trunk push Rome.podspec
Updating spec repo `master`
Validating podspec
 -> Rome (0.15.0.43)
    - WARN  | license: Unable to find a license file
    - ERROR | [tvOS] unknown: Encountered an unknown error (Malformed version number string ) during validation.
```

With `--verbose`

```
Integrating client project

[!] Please close any current Xcode sessions and use `App.xcworkspace` for this project from now on.

Integrating target `Pods-App` (`../../../../../../var/folders/b4/qz7m1r9x3mj1bm3nfsjjf64m0000gp/T/CocoaPods-Lint-20180525-26566-3kmp1d-Rome/App.xcodeproj` project)
  Adding Build Phase '[CP] Check Pods Manifest.lock' to project.
  - Running post install hooks

-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with `xcodebuild`.

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/Tommaso/.rvm/gems/ruby-2.5.1/bin/pod trunk push Rome.podspec --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/Tommaso/.rvm/rubies/ruby-2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 43949a8804cdfb8286d56e27ea44a0b79dff22ac
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Error

```
FrozenError - can't modify frozen String
/Users/Tommaso/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:335:in `rescue in perform_extensive_analysis'
/Users/Tommaso/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:301:in `perform_extensive_analysis'
/Users/Tommaso/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:87:in `validate'
/Users/Tommaso/.rvm/gems/ruby-2.5.1/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/push.rb:125:in `validate_podspec'
/Users/Tommaso/.rvm/gems/ruby-2.5.1/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/push.rb:68:in `run'
/Users/Tommaso/.rvm/gems/ruby-2.5.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/Tommaso/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/Tommaso/.rvm/gems/ruby-2.5.1/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/Users/Tommaso/.rvm/gems/ruby-2.5.1/bin/pod:23:in `load'
/Users/Tommaso/.rvm/gems/ruby-2.5.1/bin/pod:23:in `<main>'
/Users/Tommaso/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/Users/Tommaso/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=can%27t+modify+frozen+String&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Error: can't modify frozen String
   https://github.com/CocoaPods/CocoaPods/issues/1444 [closed] [7 comments]
   06 May 2016
```

**Comment by thii** [comment]
@blender What did you get with `pod lib lint --allow-warnings`?

I ran the podspec lint on my Mac and it passed. I'm guessing the error is because you don't have any tvOS simulator installed (no idea why it chose a tvOS sample to test the podspec).

**Comment by blender** [comment]
@thii  I switched to using system ruby instead or 2.5.1 and it works...

https://cocoapods.org/pods/Rome

**Comment by thii** [comment]
@blender Thanks a lot!

**Pull request merged**
