### PR TITLE
Romefile yaml

### PR DESCRIPTION
**Pull request by blender**
- [x] rename a few ugly things
- [x] conform to ToJSON and FromJSON or Derive via Generics
- [x] make sure both INI and YAML Romefile formats are supported. Prefer Romefile in YAML
- [x] migrate with `rome utils migrate-romefile`
- [x] acceptance tests

Yaml example:

```yaml
respositoryMap:
- cat-framework: #look ma, 2 targets
  - name: AwesomeCats # target 1
     type: dynamic # can omit this key, default is dynamic
  - name: StaticKitties # target 2
     type: static  # if static, specify it
- HockeySDK-iOS:
  - name: HockeySDK # no need to specify dynamic
- dog-framework:
  - name: Doggos
     type: static # if static, specify it
ignoreMap:
- GDCWebServer:
  - name: GDCWebServer
     type: dynamic
cache:
  local: ~/Library/Caches/Rome
  s3Bucket: animals-bucket
```

### CODE REVIEW

**Comment by thii** [comment]
@blender Can INI and YAML Romefile co-exist?

**Comment by blender** [comment]
You have one Romefile. Either INI or YAML.

First it will be parsed as YAML, if that fails it will be parsed as INI. If that fails then you get a fatal error.

You can use `rome utils migrate-romefile` to automatically migrate.

**Comment by thii** [comment]
I see. I thought you have to name YAML Romefile something like `rome.yaml`.

**Comment by blender** [comment]
Nope, no change ;)

**Comment by thii** [comment]
@blender Is it possible to specify Romefile when running `rome`? We have different Romefiles for Xcode 9 and Xcode 10 due to the static frameworks support.

**Comment by blender** [comment]
@thii not at the moment. Please open an issue for this.

**Pull request merged**
